### ISSUE TITLE
Cannot Edit title when copying a copy 

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/minerva#498] opened 2022-07-05 19:47 UTC
After copying a copy, open that copy then try to copy that copy and edit a title. It will not edit as seen below, but prepend it with "Copy of "

![image](https://user-images.githubusercontent.com/2273929/177403634-b6b8b968-8c84-4251-bf5c-695733a21107.png)

response
![image](https://user-images.githubusercontent.com/2273929/177403675-cd609c7b-7650-41f9-9740-5eddcd99846a.png)

tagging @balhoff @vanaukenk @ukemi

**Comment by balhoff** [comment] 2022-07-05 19:52
If you copy a model and do not provide a title, it gets an autogenerated title "Copy of xxxxx" where xxxxx is the title of the previous model. After the model has been created, changing the title should happen as for any other model. Are you following the same approach for changing a title as usual?

**Comment by balhoff** [comment] 2022-07-05 20:00
I tested in the graph editor and can't reproduce the problem. I copied a copied model, then opened in graph editor. I used the `Model > Edit annotations` menu to delete the existing title and add a new one.

**Comment by tmushayahama** [comment] 2022-07-05 20:07
not edit title, but making a new copy based on that copy with a new title like in this payload 
![image](https://user-images.githubusercontent.com/2273929/177407348-777a3388-fcde-4b31-bb45-02cecf6e6407.png)

**Comment by tmushayahama** [comment] 2022-07-05 20:45
@balhoff lemm just use raw request and not worry about bbop

**Comment by balhoff** [comment] 2022-07-06 14:12
> @balhoff lemm just use raw request and not worry about bbop

Okay! Closing, as this seems to be primarily a client library issue. If we end up needing some specific changes to the Minerva API, let's open another ticket for that.

**Comment by tmushayahama** [comment] 2022-07-06 17:55
@balhoff @kltm I have hacked it on my side and should not be the case. It's a Minerva issue and should be fixed on the server side just like any other annotation. If it's  following its convention then adding title or state or any other operation is separate "add-annotion" operation not inside copy operation.

**Comment by vanaukenk** [comment] 2022-07-06 20:36
@tmushayahama - should I go ahead with testing on noctua-dev or will there be additional updates based on @balhoff 's comment above?

**Comment by tmushayahama** [comment] 2022-07-06 21:21
@vanaukenk oh yes, go ahead and test. this should not affect anything. It was just for development purposes

**Comment by vanaukenk** [comment] 2022-07-07 16:54
Testing today, 2022-07-07, on noctua-dev, things look okay.

**Comment by kltm** [comment] 2022-07-08 23:20
@tmushayahama To continue on here, could you put in the JSON object that you're currently building to get the title in?

**Closed** 2022-08-31 14:23 UTC
