### ISSUE TITLE
Ensure annotation properties not injected as annotation property declarations

### ISSUE THREAD

**Issue by cmungall** [geneontology/minerva#141] opened 2017-09-28 00:28 UTC

**Comment by cmungall** [comment] 2017-09-28 00:35
We have some at the moment. I believe this dates back to an OWLAPI ttl bug that was fixed, and these were injected as a one off.

Nevertheless it would be good for minerva to do some additional validation.

We may want to consider injecting OP declarations too, just to be super-safe

**Comment by cmungall** [comment] 2017-09-28 23:16
A bit more background in this doc: https://docs.google.com/document/d/1AQoBLjNFAq0jUHH7HHbnhEMVJwklw4qYG872hJIdwBw/edit#heading=h.56h0hipllk5y

**Comment by kltm** [comment] 2017-10-09 18:21
@balhoff Is this closed now, or still pending?

**Comment by balhoff** [comment] 2017-10-09 18:30
I believe we found the root cause of this, and while it would be good down the road to push for some some kind of OWL API strict mode, we can probably close this ticket.

**Closed by balhoff** 2017-10-09 18:30 UTC
