### ISSUE TITLE
Generate species GPADs using the GPI files

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#420] opened 2021-09-20 20:18 UTC
I thought I opened this ticket before I left on vacation, but can't find it. Currently MGI picks up mouse annotations by retrieving the mgi gpad file as well as the pro gpad file. In doing QC we realized that we are missing an annotation that is to a functional RNA because it doesn't get put into either of these files. My assumption is that the files are generated via the prefixes of the identifiers in the annotation (MGI, PR, etc).
This is probably a lot of work, but it would be more complete to generate the GPAD files based on the identifiers in a given group's GPI file. 

Here is an example of such an annotation. They are rare, but exist.
RefSeq:NR_028355 |   | RO:0002327 | GO:0030374 | MGI:MGI:3050934\|PMID:15180993 | ECO:0000314 |   |   | 2020-11-17 | MGI |   | creation-date=2009-11-13\|modification-date=2020-11-17\|comment=The RNA transcript itself  not it's protein  is what is activating\|contributor-id=https://orcid.org/0000-0003-2689-5511 |   |  

Here is the line from the MGI GPI file:
RefSeq:NR_028355	NR_028355			SO:0000234	NCBITaxon:10090	MGI:MGI:1344414

Note that it is imported correctly:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_1344414

@linimgi this corresponds to line 38 on your QC spreadsheet.

**Comment by balhoff** [comment] 2021-09-21 16:33
Making a note because it took me a little while to remember where the code for this is: 

- Each Noctua model is individually exported to GPAD from Minerva.
  - Runs in the pipeline here: https://github.com/geneontology/pipeline/blob/4a1f5a53c6a6569afc014dc7fe31bcd651ed14fe/Jenkinsfile#L463
- A script is then used to collate into groups: https://github.com/geneontology/noctua-models/blob/master/util/collate-gpads.pl
  - This is run in the pipeline here: https://github.com/geneontology/pipeline/blob/4a1f5a53c6a6569afc014dc7fe31bcd651ed14fe/Jenkinsfile#L467

**Comment by ukemi** [comment] 2021-09-22 13:56
@balhoff, based on your comment yesterday, I did a bit more digging and you were right! These annotations are getting parsed into separate files. Here is the one above from the refseq file. There is also an embl file. It still seems like a silly way to split the data.

RefSeq	NR_028355	enables	GO:0030374	PMID:15180993	ECO:0000314			20201117	MGI		noctua-model-id=gomodel:MGI_MGI_1344414|contributor=https://orcid.org/0000-0003-2689-5511|model-state=production|creation-date=2009-11-13|import-date=2021-08-09

**Comment by ukemi** [comment] 2021-09-22 13:59
PS. It really does look like they are being parsed just based on prefix.

**Comment by balhoff** [comment] 2021-09-22 14:33
> PS. It really does look like they are being parsed just based on prefix.

I think maybe the collation script could parse out the provider group instead. Would that work?

**Comment by vanaukenk** [comment] 2021-12-15 00:52
This ticket is a duplicate of a pipeline tracker ticket:  https://github.com/geneontology/pipeline/issues/246
Closing this one, but referencing this ticket there.

**Closed by vanaukenk** 2021-12-15 00:52 UTC
Labels: GAF/GPAD, pipeline
